version: '1.0'

services:
  web:
    build: ./src
    command: |
      sh -c 'uvicorn app.main:server.get_app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://hero_dev:hero_dev@db/hero
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hero_dev
      - POSTGRES_PASSWORD=hero_dev
      - POSTGRES_DB=hero

volumes:
  postgres_data: